#!/bin/bash

dir=$1
output_file=$2

i=0

files=$(ls $dir)
echo $files
for filename in $files; do
  echo $i
  if [ $i = 0 ] ; then
    # copy csv headers from first file
    echo "first file"
    head -n 1 $dir/$filename > $dir/$output_file
  fi
  echo $i "common part"
  # copy csv without headers from other files
  tail -n +2 $dir/$filename >> $dir/$output_file
  i=$(( $i + 1 ))
done
